// <auto-generated />
using System;
using CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProject.Migrations
{
    [DbContext(typeof(TruckerDbContext))]
    [Migration("20250302230324_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProject.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TruckerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CapstoneProject.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "item1.jpg",
                            Name = "Tire",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "item2.jpeg",
                            Name = "Oil",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "item3.jpg",
                            Name = "Brake Pads",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "item4.jpg",
                            Name = "Wiper Blades",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruckerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CapstoneProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TruckerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CapstoneProject.Models.Trucker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TruckerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Truckers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Kuljeet",
                            LastName = "Singh Sidhu",
                            TotalSpent = 0m,
                            TruckerId = "9362"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Gurpreet",
                            LastName = "Singh Kooner",
                            TotalSpent = 0m,
                            TruckerId = "9386"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "9394"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "9406"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9412"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9414"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Manjinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9416"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9420"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9422"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jatinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9424"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9430"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9432"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Preetinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9436"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Tarinder",
                            LastName = "Singh Dosanjh",
                            TotalSpent = 0m,
                            TruckerId = "9438"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Balwinder",
                            LastName = "Singh Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "9440"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Tarinder",
                            LastName = "Singh Dosanjh",
                            TotalSpent = 0m,
                            TruckerId = "9442"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Jasmeet",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "9446"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Simratpal",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9452"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Harjinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9460"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Sidhant",
                            LastName = "Sharda",
                            TotalSpent = 0m,
                            TruckerId = "9462"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "9464"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9466"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9468"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9470"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9472"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9474"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9476"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Lawan",
                            LastName = "Kapoor",
                            TotalSpent = 0m,
                            TruckerId = "9478"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Tarinder",
                            LastName = "Singh Dosanjh",
                            TotalSpent = 0m,
                            TruckerId = "9480"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9484"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9486"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9488"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Jasmeet",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "9490"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Gurpreet",
                            LastName = "Singh Kooner",
                            TotalSpent = 0m,
                            TruckerId = "9492"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9494"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Amanjot",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9498"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9500"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Kuljit",
                            LastName = "Singh .",
                            TotalSpent = 0m,
                            TruckerId = "9502"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Gurpreet",
                            LastName = "Singh Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9504"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9506"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9508"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9510"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "9512"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Gurpreet",
                            LastName = "Singh Kooner",
                            TotalSpent = 0m,
                            TruckerId = "9514"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9516"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Gurpreet",
                            LastName = "Singh Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9518"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Akashdeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9522"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Roop Kamal",
                            LastName = "Singh Mand",
                            TotalSpent = 0m,
                            TruckerId = "9526"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Harpreet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9534"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Gurpreet",
                            LastName = "Singh Kooner",
                            TotalSpent = 0m,
                            TruckerId = "9538"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Manjinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9544"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Balkaran",
                            LastName = "Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "9546"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Vikramjit",
                            LastName = "Singh Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "9548"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Jobanpreet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9552"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Navpreet",
                            LastName = "Singh Randhay",
                            TotalSpent = 0m,
                            TruckerId = "9554"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Akashdeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "9556"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "156"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Jatinder",
                            LastName = "Singh Bains",
                            TotalSpent = 0m,
                            TruckerId = "158"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "162"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "164"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Paramjit",
                            LastName = "Singh Ghuman",
                            TotalSpent = 0m,
                            TruckerId = "170"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "174"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "176"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "178"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "186"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "188"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Chamkaur",
                            LastName = "Singh Kaile",
                            TotalSpent = 0m,
                            TruckerId = "189"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "190"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Sukhpreet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "194"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Harcharan",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "198"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Manjinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "200"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "202"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Harmanpreet",
                            LastName = "Bajwa",
                            TotalSpent = 0m,
                            TruckerId = "204"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Jaspal",
                            LastName = "Gill",
                            TotalSpent = 0m,
                            TruckerId = "206"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Jaskarn",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "208"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "212"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Rajender",
                            LastName = "Singh Dhesi",
                            TotalSpent = 0m,
                            TruckerId = "214"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Sami",
                            LastName = "Mohamed Gharbiya",
                            TotalSpent = 0m,
                            TruckerId = "220"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "222"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "224"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "226"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "228"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "230"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "234"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "236"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Lovepreet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "238"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Yadwinder",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "240"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "244"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Jaskarn",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "246"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "250"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "252"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Manveer",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "258"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Jagmeet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "260"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Gurjit",
                            LastName = "Singh Chahal",
                            TotalSpent = 0m,
                            TruckerId = "262"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Jaskarn",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "264"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "266"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "270"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "272"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "274"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "276"
                        },
                        new
                        {
                            Id = 101,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "278"
                        },
                        new
                        {
                            Id = 102,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa",
                            TotalSpent = 0m,
                            TruckerId = "280"
                        },
                        new
                        {
                            Id = 103,
                            FirstName = "Luis",
                            LastName = "S Azevedo",
                            TotalSpent = 0m,
                            TruckerId = "282"
                        },
                        new
                        {
                            Id = 104,
                            FirstName = "Gurpreet",
                            LastName = "Singh Dhillon",
                            TotalSpent = 0m,
                            TruckerId = "284"
                        },
                        new
                        {
                            Id = 105,
                            FirstName = "Pawanpreet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "286"
                        },
                        new
                        {
                            Id = 106,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "288"
                        },
                        new
                        {
                            Id = 107,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "290"
                        },
                        new
                        {
                            Id = 108,
                            FirstName = "Ravinder",
                            LastName = "Jaswal",
                            TotalSpent = 0m,
                            TruckerId = "292"
                        },
                        new
                        {
                            Id = 109,
                            FirstName = "Gurvinder",
                            LastName = "Pannu",
                            TotalSpent = 0m,
                            TruckerId = "294"
                        },
                        new
                        {
                            Id = 110,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "300"
                        },
                        new
                        {
                            Id = 111,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "302"
                        },
                        new
                        {
                            Id = 112,
                            FirstName = "Chetanbir",
                            LastName = "Sohal",
                            TotalSpent = 0m,
                            TruckerId = "304"
                        },
                        new
                        {
                            Id = 113,
                            FirstName = "Satnam",
                            LastName = "Singh Saini",
                            TotalSpent = 0m,
                            TruckerId = "312"
                        },
                        new
                        {
                            Id = 114,
                            FirstName = "Hardeep",
                            LastName = "Singh Dhaliwal",
                            TotalSpent = 0m,
                            TruckerId = "314"
                        },
                        new
                        {
                            Id = 115,
                            FirstName = "Kulwinder",
                            LastName = "Singh Bagga",
                            TotalSpent = 0m,
                            TruckerId = "316"
                        },
                        new
                        {
                            Id = 116,
                            FirstName = "Amrik",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "318"
                        },
                        new
                        {
                            Id = 117,
                            FirstName = "Karminder",
                            LastName = "Singh Cheema",
                            TotalSpent = 0m,
                            TruckerId = "324"
                        },
                        new
                        {
                            Id = 118,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "326"
                        },
                        new
                        {
                            Id = 119,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "328"
                        },
                        new
                        {
                            Id = 120,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "330"
                        },
                        new
                        {
                            Id = 121,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "332"
                        },
                        new
                        {
                            Id = 122,
                            FirstName = "Himmat",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "334"
                        },
                        new
                        {
                            Id = 123,
                            FirstName = "Hardeep",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "336"
                        },
                        new
                        {
                            Id = 124,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "338"
                        },
                        new
                        {
                            Id = 125,
                            FirstName = "Balraj",
                            LastName = "Singh Gill",
                            TotalSpent = 0m,
                            TruckerId = "340"
                        },
                        new
                        {
                            Id = 126,
                            FirstName = "Manveer",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "342"
                        },
                        new
                        {
                            Id = 127,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal",
                            TotalSpent = 0m,
                            TruckerId = "344"
                        },
                        new
                        {
                            Id = 128,
                            FirstName = "Bahadur",
                            LastName = "Singh Thiara",
                            TotalSpent = 0m,
                            TruckerId = "1320"
                        },
                        new
                        {
                            Id = 129,
                            FirstName = "Rajvir",
                            LastName = "Singh Sagi",
                            TotalSpent = 0m,
                            TruckerId = "1339"
                        },
                        new
                        {
                            Id = 130,
                            FirstName = "Hardeep 1416",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "1416"
                        },
                        new
                        {
                            Id = 131,
                            FirstName = "Jaskirandeep",
                            LastName = "Singh Gill",
                            TotalSpent = 0m,
                            TruckerId = "1524"
                        },
                        new
                        {
                            Id = 132,
                            FirstName = "Chaudhery Amir",
                            LastName = "Amin Bajwa",
                            TotalSpent = 0m,
                            TruckerId = "1550"
                        },
                        new
                        {
                            Id = 133,
                            FirstName = "Gurvinder",
                            LastName = "Singh Kahlon",
                            TotalSpent = 0m,
                            TruckerId = "1620"
                        },
                        new
                        {
                            Id = 134,
                            FirstName = "Kulwant",
                            LastName = "Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "1628"
                        },
                        new
                        {
                            Id = 135,
                            FirstName = "Gurbhej",
                            LastName = "Singh Kahlon",
                            TotalSpent = 0m,
                            TruckerId = "1642"
                        },
                        new
                        {
                            Id = 136,
                            FirstName = "Gurpreet",
                            LastName = "Singh Shergill",
                            TotalSpent = 0m,
                            TruckerId = "1646"
                        },
                        new
                        {
                            Id = 137,
                            FirstName = "Jan",
                            LastName = "Wyzga",
                            TotalSpent = 0m,
                            TruckerId = "1658"
                        },
                        new
                        {
                            Id = 138,
                            FirstName = "Mervin Walton",
                            LastName = "Robinson",
                            TotalSpent = 0m,
                            TruckerId = "1660"
                        },
                        new
                        {
                            Id = 139,
                            FirstName = "Jun",
                            LastName = "Zhu",
                            TotalSpent = 0m,
                            TruckerId = "1662"
                        },
                        new
                        {
                            Id = 140,
                            FirstName = "Kulwant Singh",
                            LastName = "Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "1664"
                        },
                        new
                        {
                            Id = 141,
                            FirstName = "Kulwant Singh",
                            LastName = "Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "1666"
                        },
                        new
                        {
                            Id = 142,
                            FirstName = "Radhe Sham",
                            LastName = "Thind",
                            TotalSpent = 0m,
                            TruckerId = "904150"
                        },
                        new
                        {
                            Id = 143,
                            FirstName = "Shahid",
                            LastName = "Rashid",
                            TotalSpent = 0m,
                            TruckerId = "907120"
                        },
                        new
                        {
                            Id = 144,
                            FirstName = "Kanwaljot Singh",
                            LastName = "Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "916136"
                        },
                        new
                        {
                            Id = 145,
                            FirstName = "Jaspal",
                            LastName = "Brar",
                            TotalSpent = 0m,
                            TruckerId = "919128"
                        },
                        new
                        {
                            Id = 146,
                            FirstName = "Ishneet Paul",
                            LastName = "Singh Sandhu",
                            TotalSpent = 0m,
                            TruckerId = "919134"
                        },
                        new
                        {
                            Id = 147,
                            FirstName = "Jaspal",
                            LastName = "Brar",
                            TotalSpent = 0m,
                            TruckerId = "919135"
                        },
                        new
                        {
                            Id = 148,
                            FirstName = "Jaspal",
                            LastName = "Brar",
                            TotalSpent = 0m,
                            TruckerId = "919137"
                        },
                        new
                        {
                            Id = 149,
                            FirstName = "Jaspal",
                            LastName = "Brar",
                            TotalSpent = 0m,
                            TruckerId = "919138"
                        },
                        new
                        {
                            Id = 150,
                            FirstName = "Zauhar Alankar",
                            LastName = "Gill",
                            TotalSpent = 0m,
                            TruckerId = "920127"
                        },
                        new
                        {
                            Id = 151,
                            FirstName = "Kapil Kumar",
                            LastName = "Muttan",
                            TotalSpent = 0m,
                            TruckerId = "920142"
                        },
                        new
                        {
                            Id = 152,
                            FirstName = "Sumanjot",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "920145"
                        },
                        new
                        {
                            Id = 153,
                            FirstName = "Simranjeet",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "920155"
                        },
                        new
                        {
                            Id = 154,
                            FirstName = "Kanwarbir",
                            LastName = "Singh",
                            TotalSpent = 0m,
                            TruckerId = "920157"
                        },
                        new
                        {
                            Id = 155,
                            FirstName = "Akshay",
                            LastName = "Kumar",
                            TotalSpent = 0m,
                            TruckerId = "921154"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Invoice", b =>
                {
                    b.HasOne("CapstoneProject.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany()
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany()
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.OrderItem", b =>
                {
                    b.HasOne("CapstoneProject.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.HasOne("CapstoneProject.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany("Transactions")
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CapstoneProject.Models.Trucker", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
