// <auto-generated />
using System;
using CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProject.Migrations
{
    [DbContext(typeof(TruckerDbContext))]
    partial class TruckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProject.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TruckerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CapstoneProject.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "item1.jpg",
                            Name = "Tire",
                            Price = 120.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "item2.jpeg",
                            Name = "Oil",
                            Price = 40.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "item3.jpg",
                            Name = "Brake Pads",
                            Price = 70.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "item4.jpg",
                            Name = "Wiper Blades",
                            Price = 25.00m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruckerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CapstoneProject.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TruckerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CapstoneProject.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TruckNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TruckerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruckerId");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TruckNumber = "9362",
                            TruckerId = 1
                        },
                        new
                        {
                            Id = 2,
                            TruckNumber = "9386",
                            TruckerId = 2
                        },
                        new
                        {
                            Id = 3,
                            TruckNumber = "9394",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 4,
                            TruckNumber = "9406",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 5,
                            TruckNumber = "9412",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 6,
                            TruckNumber = "9414",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 7,
                            TruckNumber = "9416",
                            TruckerId = 6
                        },
                        new
                        {
                            Id = 8,
                            TruckNumber = "9420",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 9,
                            TruckNumber = "9422",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 10,
                            TruckNumber = "9424",
                            TruckerId = 7
                        },
                        new
                        {
                            Id = 11,
                            TruckNumber = "9430",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 12,
                            TruckNumber = "9432",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 13,
                            TruckNumber = "9436",
                            TruckerId = 8
                        },
                        new
                        {
                            Id = 14,
                            TruckNumber = "9438",
                            TruckerId = 9
                        },
                        new
                        {
                            Id = 15,
                            TruckNumber = "9440",
                            TruckerId = 10
                        },
                        new
                        {
                            Id = 16,
                            TruckNumber = "9442",
                            TruckerId = 9
                        },
                        new
                        {
                            Id = 17,
                            TruckNumber = "9446",
                            TruckerId = 11
                        },
                        new
                        {
                            Id = 18,
                            TruckNumber = "9452",
                            TruckerId = 12
                        },
                        new
                        {
                            Id = 19,
                            TruckNumber = "9460",
                            TruckerId = 13
                        },
                        new
                        {
                            Id = 20,
                            TruckNumber = "9462",
                            TruckerId = 14
                        },
                        new
                        {
                            Id = 21,
                            TruckNumber = "9464",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 22,
                            TruckNumber = "9466",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 23,
                            TruckNumber = "9468",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 24,
                            TruckNumber = "9470",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 25,
                            TruckNumber = "9472",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 26,
                            TruckNumber = "9474",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 27,
                            TruckNumber = "9476",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 28,
                            TruckNumber = "9478",
                            TruckerId = 17
                        },
                        new
                        {
                            Id = 29,
                            TruckNumber = "9480",
                            TruckerId = 9
                        },
                        new
                        {
                            Id = 30,
                            TruckNumber = "9484",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 31,
                            TruckNumber = "9486",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 32,
                            TruckNumber = "9488",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 33,
                            TruckNumber = "9490",
                            TruckerId = 11
                        },
                        new
                        {
                            Id = 34,
                            TruckNumber = "9492",
                            TruckerId = 2
                        },
                        new
                        {
                            Id = 35,
                            TruckNumber = "9494",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 36,
                            TruckNumber = "9498",
                            TruckerId = 19
                        },
                        new
                        {
                            Id = 37,
                            TruckNumber = "9500",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 38,
                            TruckNumber = "9502",
                            TruckerId = 20
                        },
                        new
                        {
                            Id = 39,
                            TruckNumber = "9504",
                            TruckerId = 21
                        },
                        new
                        {
                            Id = 40,
                            TruckNumber = "9506",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 41,
                            TruckNumber = "9508",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 42,
                            TruckNumber = "9510",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 43,
                            TruckNumber = "9512",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 44,
                            TruckNumber = "9514",
                            TruckerId = 2
                        },
                        new
                        {
                            Id = 45,
                            TruckNumber = "9516",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 46,
                            TruckNumber = "9518",
                            TruckerId = 21
                        },
                        new
                        {
                            Id = 47,
                            TruckNumber = "9522",
                            TruckerId = 22
                        },
                        new
                        {
                            Id = 48,
                            TruckNumber = "9526",
                            TruckerId = 23
                        },
                        new
                        {
                            Id = 49,
                            TruckNumber = "9534",
                            TruckerId = 24
                        },
                        new
                        {
                            Id = 50,
                            TruckNumber = "9538",
                            TruckerId = 2
                        },
                        new
                        {
                            Id = 51,
                            TruckNumber = "9544",
                            TruckerId = 6
                        },
                        new
                        {
                            Id = 52,
                            TruckNumber = "9546",
                            TruckerId = 18
                        },
                        new
                        {
                            Id = 53,
                            TruckNumber = "9548",
                            TruckerId = 25
                        },
                        new
                        {
                            Id = 54,
                            TruckNumber = "9552",
                            TruckerId = 26
                        },
                        new
                        {
                            Id = 55,
                            TruckNumber = "9554",
                            TruckerId = 27
                        },
                        new
                        {
                            Id = 56,
                            TruckNumber = "9556",
                            TruckerId = 22
                        },
                        new
                        {
                            Id = 57,
                            TruckNumber = "156",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 58,
                            TruckNumber = "158",
                            TruckerId = 28
                        },
                        new
                        {
                            Id = 59,
                            TruckNumber = "162",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 60,
                            TruckNumber = "164",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 61,
                            TruckNumber = "170",
                            TruckerId = 29
                        },
                        new
                        {
                            Id = 62,
                            TruckNumber = "174",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 63,
                            TruckNumber = "176",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 64,
                            TruckNumber = "178",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 65,
                            TruckNumber = "186",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 66,
                            TruckNumber = "188",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 67,
                            TruckNumber = "189",
                            TruckerId = 30
                        },
                        new
                        {
                            Id = 68,
                            TruckNumber = "190",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 69,
                            TruckNumber = "194",
                            TruckerId = 31
                        },
                        new
                        {
                            Id = 70,
                            TruckNumber = "198",
                            TruckerId = 32
                        },
                        new
                        {
                            Id = 71,
                            TruckNumber = "200",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 72,
                            TruckNumber = "202",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 73,
                            TruckNumber = "204",
                            TruckerId = 34
                        },
                        new
                        {
                            Id = 74,
                            TruckNumber = "206",
                            TruckerId = 35
                        },
                        new
                        {
                            Id = 75,
                            TruckNumber = "208",
                            TruckerId = 36
                        },
                        new
                        {
                            Id = 76,
                            TruckNumber = "212",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 77,
                            TruckNumber = "214",
                            TruckerId = 37
                        },
                        new
                        {
                            Id = 78,
                            TruckNumber = "220",
                            TruckerId = 38
                        },
                        new
                        {
                            Id = 79,
                            TruckNumber = "222",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 80,
                            TruckNumber = "224",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 81,
                            TruckNumber = "226",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 82,
                            TruckNumber = "228",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 83,
                            TruckNumber = "230",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 84,
                            TruckNumber = "234",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 85,
                            TruckNumber = "236",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 86,
                            TruckNumber = "238",
                            TruckerId = 40
                        },
                        new
                        {
                            Id = 87,
                            TruckNumber = "240",
                            TruckerId = 5
                        },
                        new
                        {
                            Id = 88,
                            TruckNumber = "244",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 89,
                            TruckNumber = "246",
                            TruckerId = 36
                        },
                        new
                        {
                            Id = 90,
                            TruckNumber = "250",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 91,
                            TruckNumber = "252",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 92,
                            TruckNumber = "258",
                            TruckerId = 41
                        },
                        new
                        {
                            Id = 93,
                            TruckNumber = "260",
                            TruckerId = 42
                        },
                        new
                        {
                            Id = 94,
                            TruckNumber = "262",
                            TruckerId = 43
                        },
                        new
                        {
                            Id = 95,
                            TruckNumber = "264",
                            TruckerId = 36
                        },
                        new
                        {
                            Id = 96,
                            TruckNumber = "266",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 97,
                            TruckNumber = "270",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 98,
                            TruckNumber = "272",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 99,
                            TruckNumber = "274",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 100,
                            TruckNumber = "276",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 101,
                            TruckNumber = "278",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 102,
                            TruckNumber = "280",
                            TruckerId = 33
                        },
                        new
                        {
                            Id = 103,
                            TruckNumber = "282",
                            TruckerId = 3
                        },
                        new
                        {
                            Id = 104,
                            TruckNumber = "284",
                            TruckerId = 21
                        },
                        new
                        {
                            Id = 105,
                            TruckNumber = "286",
                            TruckerId = 44
                        },
                        new
                        {
                            Id = 106,
                            TruckNumber = "288",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 107,
                            TruckNumber = "290",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 108,
                            TruckNumber = "292",
                            TruckerId = 4
                        },
                        new
                        {
                            Id = 109,
                            TruckNumber = "294",
                            TruckerId = 45
                        },
                        new
                        {
                            Id = 110,
                            TruckNumber = "300",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 111,
                            TruckNumber = "302",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 112,
                            TruckNumber = "304",
                            TruckerId = 15
                        },
                        new
                        {
                            Id = 113,
                            TruckNumber = "312",
                            TruckerId = 46
                        },
                        new
                        {
                            Id = 114,
                            TruckNumber = "314",
                            TruckerId = 47
                        },
                        new
                        {
                            Id = 115,
                            TruckNumber = "316",
                            TruckerId = 48
                        },
                        new
                        {
                            Id = 116,
                            TruckNumber = "318",
                            TruckerId = 49
                        },
                        new
                        {
                            Id = 117,
                            TruckNumber = "324",
                            TruckerId = 50
                        },
                        new
                        {
                            Id = 118,
                            TruckNumber = "326",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 119,
                            TruckNumber = "328",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 120,
                            TruckNumber = "330",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 121,
                            TruckNumber = "332",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 122,
                            TruckNumber = "334",
                            TruckerId = 51
                        },
                        new
                        {
                            Id = 123,
                            TruckNumber = "336",
                            TruckerId = 16
                        },
                        new
                        {
                            Id = 124,
                            TruckNumber = "338",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 125,
                            TruckNumber = "340",
                            TruckerId = 52
                        },
                        new
                        {
                            Id = 126,
                            TruckNumber = "342",
                            TruckerId = 41
                        },
                        new
                        {
                            Id = 127,
                            TruckNumber = "344",
                            TruckerId = 39
                        },
                        new
                        {
                            Id = 128,
                            TruckNumber = "1320",
                            TruckerId = 53
                        },
                        new
                        {
                            Id = 129,
                            TruckNumber = "1339",
                            TruckerId = 54
                        },
                        new
                        {
                            Id = 130,
                            TruckNumber = "1416",
                            TruckerId = 55
                        },
                        new
                        {
                            Id = 131,
                            TruckNumber = "1524",
                            TruckerId = 56
                        },
                        new
                        {
                            Id = 132,
                            TruckNumber = "1550",
                            TruckerId = 57
                        },
                        new
                        {
                            Id = 133,
                            TruckNumber = "1620",
                            TruckerId = 58
                        },
                        new
                        {
                            Id = 134,
                            TruckNumber = "1628",
                            TruckerId = 59
                        },
                        new
                        {
                            Id = 135,
                            TruckNumber = "1642",
                            TruckerId = 60
                        },
                        new
                        {
                            Id = 136,
                            TruckNumber = "1646",
                            TruckerId = 61
                        },
                        new
                        {
                            Id = 137,
                            TruckNumber = "1658",
                            TruckerId = 62
                        },
                        new
                        {
                            Id = 138,
                            TruckNumber = "1660",
                            TruckerId = 63
                        },
                        new
                        {
                            Id = 139,
                            TruckNumber = "1662",
                            TruckerId = 64
                        },
                        new
                        {
                            Id = 140,
                            TruckNumber = "1664",
                            TruckerId = 65
                        },
                        new
                        {
                            Id = 141,
                            TruckNumber = "1666",
                            TruckerId = 65
                        },
                        new
                        {
                            Id = 142,
                            TruckNumber = "904150",
                            TruckerId = 66
                        },
                        new
                        {
                            Id = 143,
                            TruckNumber = "907120",
                            TruckerId = 67
                        },
                        new
                        {
                            Id = 144,
                            TruckNumber = "916136",
                            TruckerId = 68
                        },
                        new
                        {
                            Id = 145,
                            TruckNumber = "919128",
                            TruckerId = 69
                        },
                        new
                        {
                            Id = 146,
                            TruckNumber = "919134",
                            TruckerId = 70
                        },
                        new
                        {
                            Id = 147,
                            TruckNumber = "919135",
                            TruckerId = 69
                        },
                        new
                        {
                            Id = 148,
                            TruckNumber = "919137",
                            TruckerId = 69
                        },
                        new
                        {
                            Id = 149,
                            TruckNumber = "919138",
                            TruckerId = 69
                        },
                        new
                        {
                            Id = 150,
                            TruckNumber = "920127",
                            TruckerId = 71
                        },
                        new
                        {
                            Id = 151,
                            TruckNumber = "920142",
                            TruckerId = 72
                        },
                        new
                        {
                            Id = 152,
                            TruckNumber = "920145",
                            TruckerId = 73
                        },
                        new
                        {
                            Id = 153,
                            TruckNumber = "920155",
                            TruckerId = 74
                        },
                        new
                        {
                            Id = 154,
                            TruckNumber = "920157",
                            TruckerId = 75
                        },
                        new
                        {
                            Id = 155,
                            TruckNumber = "921154",
                            TruckerId = 76
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Trucker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Truckers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Kuljeet",
                            LastName = "Singh Sidhu"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Gurpreet",
                            LastName = "Singh Kooner"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Luis",
                            LastName = "S Azevedo"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ravinder",
                            LastName = "Jaswal"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Yadwinder",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Manjinder",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Jatinder",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Preetinder",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Tarinder",
                            LastName = "Singh Dosanjh"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Balwinder",
                            LastName = "Singh Sandhu"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Jasmeet",
                            LastName = "Singh Grewal"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Simratpal",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Harjinder",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Sidhant",
                            LastName = "Sharda"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Chetanbir",
                            LastName = "Sohal"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Hardeep",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Lawan",
                            LastName = "Kapoor"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Balkaran",
                            LastName = "Dhillon"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Amanjot",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Kuljit",
                            LastName = "Singh ."
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Gurpreet",
                            LastName = "Singh Dhillon"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Akashdeep",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Roop Kamal",
                            LastName = "Singh Mand"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Harpreet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Vikramjit",
                            LastName = "Singh Sandhu"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Jobanpreet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Navpreet",
                            LastName = "Singh Randhay"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Jatinder",
                            LastName = "Singh Bains"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Paramjit",
                            LastName = "Singh Ghuman"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Chamkaur",
                            LastName = "Singh Kaile"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Sukhpreet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Harcharan",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Kelly",
                            LastName = "Fagundes Giampapa"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Harmanpreet",
                            LastName = "Bajwa"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Jaspal",
                            LastName = "Gill"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Jaskarn",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Rajender",
                            LastName = "Singh Dhesi"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Sami",
                            LastName = "Mohamed Gharbiya"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Pardeep",
                            LastName = "Singh Grewal"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Lovepreet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Manveer",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Jagmeet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Gurjit",
                            LastName = "Singh Chahal"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Pawanpreet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Gurvinder",
                            LastName = "Pannu"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Satnam",
                            LastName = "Singh Saini"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Hardeep",
                            LastName = "Singh Dhaliwal"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Kulwinder",
                            LastName = "Singh Bagga"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Amrik",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Karminder",
                            LastName = "Singh Cheema"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Himmat",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Balraj",
                            LastName = "Singh Gill"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Bahadur",
                            LastName = "Singh Thiara"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Rajvir",
                            LastName = "Singh Sagi"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Hardeep 1416",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Jaskirandeep",
                            LastName = "Singh Gill"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Chaudhery Amir",
                            LastName = "Amin Bajwa"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Gurvinder",
                            LastName = "Singh Kahlon"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Kulwant",
                            LastName = "Sandhu"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Gurbhej",
                            LastName = "Singh Kahlon"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Gurpreet",
                            LastName = "Singh Shergill"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Jan",
                            LastName = "Wyzga"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Mervin Walton",
                            LastName = "Robinson"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Jun",
                            LastName = "Zhu"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Kulwant Singh",
                            LastName = "Sandhu"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Radhe Sham",
                            LastName = "Thind"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Shahid",
                            LastName = "Rashid"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Kanwaljot Singh",
                            LastName = "Sandhu"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Jaspal",
                            LastName = "Brar"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Ishneet Paul",
                            LastName = "Singh Sandhu"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Zauhar Alankar",
                            LastName = "Gill"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Kapil Kumar",
                            LastName = "Muttan"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Sumanjot",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Simranjeet",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Kanwarbir",
                            LastName = "Singh"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Akshay",
                            LastName = "Kumar"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Invoice", b =>
                {
                    b.HasOne("CapstoneProject.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany()
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany()
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.OrderItem", b =>
                {
                    b.HasOne("CapstoneProject.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CapstoneProject.Models.Transaction", b =>
                {
                    b.HasOne("CapstoneProject.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany("Transactions")
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.Truck", b =>
                {
                    b.HasOne("CapstoneProject.Models.Trucker", "Trucker")
                        .WithMany("Trucks")
                        .HasForeignKey("TruckerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trucker");
                });

            modelBuilder.Entity("CapstoneProject.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CapstoneProject.Models.Trucker", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
